Stratio/bdt

src/main/java/com/stratio/qa/specs/GivenGSpec.java

Fixing step to not have "matches more than one step definition" error

[DCS-1222] change regular expression

---

src/main/java/com/stratio/qa/aspects/IgnoreTagAspect.java
src/main/java/com/stratio/qa/aspects/RunOnTagAspect.java
src/main/java/com/stratio/qa/cucumber/testng/CucumberReporter.java
src/test/resources/features/loopTag.feature
src/test/resources/features/runOnEnvTag.feature

fix cucumber reporter showing scenario name & use two tags for ignoring scenarios

[QA-368] Refactor runOnEnv to use ignore aspect with two tags

---

src/main/java/com/stratio/qa/cucumber/testng/CucumberRunner.java
src/main/java/com/stratio/qa/specs/GivenGSpec.java
src/main/java/com/stratio/qa/utils/GosecSSOUtils.java
src/test/java/com/stratio/qa/utils/GosecSSOUtilsIT.java

Gosec sso token generator added. This step allows you to generate token to be used in securized environment.

[QA-396] Gosec token generator step added

---

Jenkinsfile
pom.xml
src/main/java/com/stratio/qa/specs/CommonG.java
src/main/java/com/stratio/qa/specs/GivenGSpec.java
src/main/java/com/stratio/qa/specs/ThenGSpec.java
src/main/java/com/stratio/qa/specs/WhenGSpec.java
src/main/java/com/stratio/qa/utils/LdapUtil.java
src/main/java/com/stratio/qa/utils/LdapUtils.java
src/test/java/com/stratio/qa/specs/LdapStepsIT.java
src/test/java/com/stratio/qa/utils/LdapUtilsIT.java
src/test/resources/features/ldapSteps.feature
src/test/resources/log4j2.xml

LDAP Utils and Steps for BDT. Preliminary version

[QATM-369] LDAP Utils and Steps

---

src/main/java/com/stratio/qa/cucumber/testng/CucumberRunner.java
src/main/java/com/stratio/qa/specs/ThenGSpec.java

I have included glue for new repo for governance and changes for function assertSeleniumTextOnElementPresent and check if element text matches or contains any text.

[QATM-133] Change for new repo & function for element present

---

src/main/java/com/stratio/qa/cucumber/testng/CucumberRunner.java

[SPK-225] Added custom steps for spark

---

src/main/java/com/stratio/qa/cucumber/testng/CucumberRunner.java

Changed package where the tests are stored

[SPK-248] Added spark glue with the new package configuration

---

src/main/java/com/stratio/qa/cucumber/testng/CucumberRunner.java

Spark glue to new PNF/PF locations

[SPK-248] Spark glue

---

.gitignore
CHANGELOG.md
README.md
pom.xml
src/main/java/com/stratio/qa/aspects/LoopIncludeTagAspect.java
src/test/java/com/stratio/qa/ATests/LoopTagAspectIT.java
src/test/java/com/stratio/qa/aspects/IncludeTagAspectTest.java
src/test/resources/features/multiloopTag.feature

This new tag looks for creating an Scenario Outline with all possible combinations mixing provided lists.
Basic usage:
@ multiloop(LIST1=>VAR_NAME1,LIST2=>VAR_NAME2,LIST3=>VAR_NAME3...)

[CROSSDATA-1550] Improvement: Added @multiloop tag

---

src/main/java/com/stratio/qa/cucumber/testng/CucumberRunner.java

Adding zookeeper to CucumberRunner in order to hook Zookeeper Specs

[QATM-1057] Add Zookeeper Specs to CucumberRunner

---

src/main/java/com/stratio/qa/specs/CommonG.java
src/main/java/com/stratio/qa/specs/GivenGSpec.java
src/main/java/com/stratio/qa/specs/WhenGSpec.java
src/test/java/com/stratio/qa/ATests/JsonConvertToYamlIT.java
src/test/java/com/stratio/qa/specs/CommonGTest.java
src/test/resources/features/convertJsonToYamlFile.feature

Added method to convert json to yaml

[QATM-1201] Added method to convert json to yaml

---

src/main/java/com/stratio/qa/specs/ThenGSpec.java
src/test/resources/features/selenium.feature

Add changes for search by text in selenium
Include input parameter to search element.

[QATM-1414] Add changes for search by text in selenium

---

pom.xml
src/main/java/com/stratio/qa/specs/CommonG.java
src/main/java/com/stratio/qa/specs/GivenGSpec.java

Crear step para conexion a postgres con tls

[QATM-1412] Crear step para conexion a postgres con tls

---

src/main/java/com/stratio/qa/specs/ThenGSpec.java

Added two more methods
@Then("^'(.+?)' '(.+?)' exists$")
@Then("^'(.+?)' '(.+?)' doesn't exists$")

[QATM-1431] Add sql steps to bdt

---

src/main/java/com/stratio/qa/specs/ThenGSpec.java

Incorrect name of the method connectDatabase instead closeDatabase

[QATM-1431] Refactor close database method name

---

src/main/java/com/stratio/qa/specs/CommonG.java

Se ha incluido para que en el DELETE se pueda pasar un json o no.

[QATM-1638] Incluir en el DELETE el BODY

---

src/main/java/com/stratio/qa/aspects/LoopIncludeTagAspect.java
src/main/java/com/stratio/qa/utils/BaseGTest.java
src/test/java/com/stratio/qa/ATests/LoopTagAspectIT.java
src/test/resources/features/loopTag.feature
src/test/resources/features/multiloopTag.feature

Change regex in next line
- if ((lines.get(s).toUpperCase().contains("SCENARIO")) || lines.get(s).matches(".*@[^\\{].*"))
by 
- if ((lines.get(s).toUpperCase().contains("SCENARIO")) || lines.get(s).matches("^\s[^\n|\r]@.*"))

[QATM-1643] Change regex to match for loop and multiloop

---

src/main/java/com/stratio/qa/specs/ThenGSpec.java

Se ha añadido el recurso Database para que esté step de la librería compruebe si existe o no esa base de datos.

[QATM-1646] Añadir recurso de Postgres Database

---

src/main/java/com/stratio/qa/specs/DcosSpec.java

Esta solución no es muy bonita, pero deja la implementación como estaba antes del refactor. Mergeo esto para que la nightly ejecute correctamente esta noche y mientras desarrollo una solución mejor que implicará refactor de código y mover código a CommonG

[QATM-2049] Fix for incorrect step after specs refactor

---

src/main/java/com/stratio/qa/specs/RestSpec.java

[QATM-2303] refactor of steps due to new cucumber version - delete

---

src/main/java/com/stratio/qa/specs/SeleniumSpec.java

Use in features:
And I type '${DCOS_TENANT}' if the element exists with 'xpath://*[@id="tenant"]'

[QATM-2363] Add step typing text if the element exists using selenium

---

src/main/java/com/stratio/qa/specs/CommonG.java

[QATM-2489] Added PATCH type to rest requests
[QATM-2489]: https://stratio.atlassian.net/browse/QATM-2489

[QATM-2489] Added PATCH type to rest requests

---

src/main/java/com/stratio/qa/specs/DcosSpec.java

Corregir constraints para que funcione ahora que no lo devuelve en una sola linea

[QATM-2636] Corregir constraints

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/CommandExecutionSpec.java

Implemented not contains (In less than... command out ... not contains ....

[QATM-2789] Implemented not contains in SSH Commands

---

src/main/java/com/stratio/qa/specs/SeleniumSpec.java

- Nueva función para limpiar un campo de texto utilizando el teclado

[QATM-2367] New clear function with keys Control and Delete

---

src/main/java/com/stratio/qa/specs/RestSpec.java

Create step to get id from tag policies

[SECTY-1482] Create step to get id from tag policies

---

src/main/java/com/stratio/qa/specs/RestSpec.java

[SECTY] Added step to get profileId from profileName

[SECTY-1482] Added step to get profileId from profileName

---

src/main/java/com/stratio/qa/specs/DcosSpec.java
src/main/java/com/stratio/qa/utils/GosecSSOUtils.java

Include no host name verification option in "set sso token" step.

[ROCK-612] Feature/no host verifier

---

src/main/java/com/stratio/qa/specs/CommonG.java

Add X-RolesID header for request to governanceAPI 1.2

[QATM-3006] Add X-RolesID header for governanceAPI 1.2

---

src/main/java/com/stratio/qa/specs/DcosSpec.java
src/main/java/com/stratio/qa/utils/GosecSSOUtils.java
src/test/java/com/stratio/qa/utils/GosecSSOUtilsIT.java

Modificación del step "I set sso token..." para poder obtener la cookie stratio-governance-auth

[QATM-3015] Set governance cookie

---

src/main/java/com/stratio/qa/specs/DcosSpec.java

Get REALM from bootstrap and save in variable EOS_REALM

[GS-1707] Get REALM from bootstrap and save in variable EOS_REALM

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/CommonG.java
src/main/java/com/stratio/qa/specs/RestSpec.java

Added scim type to HTTP requests

[GS-1830] Added scim type to HTTP requests

---

CHANGELOG.md
src/main/java/com/stratio/qa/cucumber/testng/CucumberRunner.java

[QATM-3165] Add gosecmanagement path to CucumberRunner
[QATM-3165]: https://stratio.atlassian.net/browse/QATM-3165

[QATM-3165] Add gosecmanagement path to CucumberRunner

---

src/main/java/com/stratio/qa/specs/HookGSpec.java
src/main/java/com/stratio/qa/specs/RestSpec.java

- Added step to get gosec variables in DCOS annotation
- Added inputSourceType creating a user in version >=1.4.0
- refactor to get GosecVersion from ThreadProperty
- Added steps to add/delete resources without path

[GS-1872] TestAT refactor for Gosec steps

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/RestSpec.java

Create Step to delete tenant if it exists

[GS-1954] Create Step to delete tenant if it exists

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/RestSpec.java

Create step to update Gosec resources
- policy
- user
- group
- tenant

[GS-1956] Create step to update Gosec resources

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/RestSpec.java

Added step to remove user or group in tenant

[GS-1957] Added step to remove user or group in tenant

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/MiscSpec.java
src/main/java/com/stratio/qa/specs/RestSpec.java
src/test/java/com/stratio/qa/specs/MiscTest.java

[GS-1965] Warning message instead of exception when gosec version not defined
[GS-1965]: https://stratio.atlassian.net/browse/GS-1965

[GS-1965] Warning message instead of exception when gosec version not defined

---

src/main/java/com/stratio/qa/specs/CCTSpec.java

He probado modificando el número de CPUs de spark en nightlyforward:
Scenario: Update service
Given I set sso token using host '!{EOS_ACCESS_POINT}' with user '!{DCOS_USER}' and password '${DCOS_PASSWORD}' and tenant '${DCOS_TENANT}'
And I securely send requests to '!{EOS_ACCESS_POINT}:443'
Then I update service 'sparkalf' in tenant 's000001' based on version '0.7.4-SNAPSHOT' with:
| $.general.resources.CPUs | REPLACE | 2 | long |

[PIT-486] add step to update deployed service

---

src/main/java/com/stratio/qa/specs/GosecSpec.java

Get profile from provided tenant

[GS-2007] Get profile from provided tenant

---

src/main/java/com/stratio/qa/specs/GosecSpec.java

Delete gosec resources using baas if exists

[GS-2046] Delete gosec resources using baas if exists

---

src/main/java/com/stratio/qa/specs/GosecSpec.java

Refactor get PolicyId step for management-baas

[GS-2111] Refactor get PolicyId step for management-baas

---

src/main/java/com/stratio/qa/specs/GosecSpec.java

https://stratio.atlassian.net/browse/GS-2118

[GS-2073] Refactor for new BaaS endpoints

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/GosecSpec.java

Added BaaS endpoints creating policies and updating resources

[GS-2033] Added BaaS endpoints creating policies and updating resources

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/MiscSpec.java
src/test/java/com/stratio/qa/ATests/TimeStampDatesIT.java
src/test/resources/features/timeStamp.feature

Convert provided date into timestamp

[GS-2354] Convert provided date into timestamp

---

src/main/java/com/stratio/qa/specs/ADFSSpec.java

add step to create simulate federated user/group

[PIT-667] Adfs management

---

src/main/java/com/stratio/qa/specs/MiscSpec.java

get correct timezone adding dates to policies

[GS-2741] get correct timezone adding dates to policies

---

CHANGELOG.md
src/main/java/com/stratio/qa/specs/ADFSSpec.java

[GS-3051] Fix check certificate creating federated users

---

CHANGELOG.md
pom.xml
src/main/java/com/stratio/qa/specs/MiscSpec.java

[GS-3161] Add step to create custom JTW

---

src/main/java/com/stratio/qa/specs/CCTSpec.java
src/main/java/com/stratio/qa/specs/CommonG.java
src/main/java/com/stratio/qa/specs/KeosSpec.java

Al mergear esta PR hay que tener cuidado, porque cambia un método que es llamado directamente desde qa-unified-tests en GovernanceSpec.java

[PQA-162] populate user cookie for rocket in k8s
