src/main/java/com/stratio/qa/utils/LdapUtils.java, src/test/resources/features/ldapSteps.feature
Due to a programming error, the LdapUtils class tried to reuse and overwrite its connection config, which after having connected to an LDAP server had been marked as immutable. This caused an unexpected exception.
This behaviour has been corrected (a new ConnectionConfig will be created each time the connect step is invoked) and a test has been added so that it can be detected in the future
=> [QATM-405] Fixed inability to connect more than once to LDAP

src/main/java/com/stratio/qa/specs/ThenGSpec.java, src/test/resources/features/ldapSteps.feature
The
@Then("^the LDAP entry contains the attribute '(.?)' with the value '(.?)'$")
step had been implemented with an assertThat().isEqualTo
This presumed the attribute was unique in a LDAP entry. However, many LDAP attributes can be present more than once (such as memberOf, once per each group the user is a member of).
Changing the implementation to return a list of Attributes instead of one and then asserting if the list contains a given attribute will produce the same result as before if the attribute is single-valued, and multivalued attributes will now be correctly processed
Sorry for the missing functionality. I should have thought of this before the initial PR :(
=> [QATM-419] Search for multivalued attributes in LDAP

src/main/java/com/stratio/qa/specs/GivenGSpec.java, src/main/java/com/stratio/qa/utils/RemoteSSHConnection.java
For Mac Users, it's not possible to establish a ssh connection with dcos-cli docker using docker IP and port 22. Therefore, acceptance tests cannot be executed locally.
This PR adds the remote port parameter to the SSH Connection.
More info here: https://stackoverflow.com/questions/37965790/how-do-i-ssh-to-a-docker-in-mac-container
=> [QATM-809] Configurable port for SSH connection

src/main/java/com/stratio/qa/specs/CommonG.java
Details:
Fix an error with selenium screanshot:
Method threw 'java.lang.IllegalArgumentException' exception.
Width (1301) and height (0) cannot be <= 0
=> [QATM-940] Control adjustLastCapture in Selenium snapshot

src/main/java/com/stratio/qa/aspects/RunOnTagAspect.java, src/test/java/com/stratio/qa/aspects/RunOnEnvTagAspectTest.java
With this change we can make it easier to install different versions of a package using the config file, checking for the value of parameter VERSION:
Example:
Feature: Install framework
@runOnEnv(VERSION=1.0.0)
Scenario: Prepare config file
...
And I create file 'config.json' based on 'schemas/eos-kafka-framework_config_${VERSION}.json' as 'json' with:
| $.specific.parameter.version.1.0.0                         | UPDATE  | ${KEY:-value}      | n/a |
...
@runOnEnv(VERSION=1.1.0)
Scenario: Prepare config file
...
And I create file 'config.json' based on 'schemas/eos-kafka-framework_config_${VERSION}.json' as 'json' with:
| $.specific.parameter.version.1.1.0                         | UPDATE  | ${KEY:-value}      | n/a |
...
Scenario: Install using dcos-cli
When I run 'dcos package install …
=> [QATM-987] able to run or skip based on value, not existance

src/main/java/com/stratio/qa/specs/CommonG.java, src/test/java/com/stratio/qa/specs/CommonGTest.java, src/test/resources/features/jsonReplacements.feature
When modifying data in a json, we need the option to add new fields to the json of a specific type:
{"key1": "value1", "key2": "value2"}
| $.newkey | ADD | true | string | -> {"key1": "value1", "key2": "value2", "newkey": "true"}
| $.newkey | ADD | {} | object | -> {"key1": "value1", "key2": "value2", "newkey": {}}
| $.newkey | ADD | true | boolean | -> {"key1": "value1", "key2": "value2", "newkey": true}
| $.newkey | ADD | 3 | number | -> {"key1": "value1", "key2": "value2", "newkey": 3}
=> [QATM-988] add possibility to add fields to json with type

src/main/java/com/stratio/qa/specs/ThenGSpec.java, src/test/java/com/stratio/qa/specs/ThenGIT.java, src/test/resources/features/assertCommandExistsOnTimeOutIT.feature
Add posibility to check exitStatus in assertCommandExistsOnTimeOut method in order to control false positives.
=> [QATM-986] AssertCommandExistsOnTimeOut - Add positiblity of check exitStatus

src/main/java/com/stratio/qa/utils/ThreadProperty.java
We would need to implement a clear method in ThreadLocal class in order to clean ThreadProperty object after each step execution. We have observed after launching two steps that make use of the method selectData (I query the database with , for example), if the first one have more columns that second one, the first result overlaps the last.
=> [QATM-1042] Add remove method

CHANGELOG.md, pom.xml
Updated commons-lang3 version to 3.7.
Crossdata testsAT are failing due to this issue.
=> [PIT-68] Updated commons-lang3 version to 3.7

src/main/java/com/stratio/qa/specs/CommonG.java, src/main/java/com/stratio/qa/specs/ThenGSpec.java, src/main/java/com/stratio/qa/specs/WhenGSpec.java
New steps added to bdt
- I execute query %
- I query the database with %
- table '(.+?)' exists
- table '(.+?)' doesn't exists
- I check that table '(.+?)' is iqual to $
- I close database connection
- ^I check that result is:$
=> [QATM-1431] Add sql steps to bdt

.gitignore, src/main/java/com/stratio/qa/specs/CommonG.java, src/main/java/com/stratio/qa/specs/GivenGSpec.java
Se ha eliminado del step de conexión a base de datos la palabra securely y se ha incluido el tipo de seguridad.
=> [QATM-1689] Sustituir en la conexion a base de datos securely por el tipo de seguridad 

src/main/java/com/stratio/qa/aspects/RunOnTagAspect.java, src/test/java/com/stratio/qa/aspects/RunOnEnvTagAspectTest.java
Se ha añadido para poder utilizar > o < en el RunOnEnv y SkipOnEnv, añadiendo tambien pruebas sobre esto.
=> [QATM-1827] Añadir < y > en las condiciones del RunOnEnv y SkipOnEnv

src/main/java/com/stratio/qa/aspects/RunOnTagAspect.java
Se corrige un error en RunOnTagAspect en la funcion checkParams, en vez de return era result=
=> [QATM-1842] Corregir error result por return en checkParams al tener operadores logicos

src/main/java/com/stratio/qa/specs/DcosSpec.java
Se ha creado un nuevo step en la librería:
The role '<role>' of the service '<service>' with instance '<instance>' complies the constraints '<constraint>'
<role> es el role de los nodos a comprobar si cumplen una constraint
<service> es el servicio perteneciente al nombre de ese servicio en el exhibitor
<instance> nombre con el que se desplegó el servicio
<constraint> pueden ser una o varias constraints separadas por “,”
=> [QATM-2178] Creación step para la comprobación de constraints de un role de un servicio de una instancia determinada

src/main/java/com/stratio/qa/specs/RestSpec.java
- Allows method with/without 'if it does not exist'
- Change name 'endpoint' to 'using API service path'
- Enum values for valid resources: policy, user or group
- Added warning message message when resource is already created
=> [QATM-2303] refactor of steps due to new cucumber version

CHANGELOG.md, src/main/java/com/stratio/qa/utils/RemoteSSHConnection.java, src/test/resources/features/readWebElementTextToVariable.feature
* No problems if host has changed the public key (may be a security issue in production, but not for testing purposes)
* Only two methods of auth: pem and password (avoiding problem with GSSAPI and others, that will hang our ssh connection)
=> [SPK-548] Enhance ssh connections

src/main/java/com/stratio/qa/specs/RestSpec.java
- Make create and delete resources methods compatible with new endpoints in gosec 1.1.1
- Added new endpoint searching policy by ID if the response is 404
=> [SECTY-1440] BDT refactor for gosec 1.1.1 new paths and ids

src/main/java/com/stratio/qa/specs/RestSpec.java, src/test/resources/features/readWebElementTextToVariable.feature
- From version 1.3.0, management API for creation/deletion of users, calls identties-daas and its http response code when a user is deleted is defined as '204' instead '200' therefore this is a change to make it compatible
=> [GS-1538] Allow response 204 deleting gosec resources

src/main/java/com/stratio/qa/specs/RestSpec.java
Al hacer las pruebas de la task force de Datio, con version de Gosec 0.16.13, se ha visto que al devolver las políticas las devuelve en un json distinto al de 0.17+
Para que los steps sean compatibles, se ha añadido que si al intentar obtener el id de una política, este es blanco, que compruebe con el método "antiguo" antes de devolver el error
=> [CROSSDATA-2345] Modify Gosec policies methods to obtain ID when Gosec < 0.17

src/main/java/com/stratio/qa/specs/CommandExecutionSpec.java
This solves the error we are seeing, but it will only allow to have 1 tunnel.
In the future we can work in a solution to have multiple tunnel connections at the same time.
=> [PIT-471] fix to avoid failure at the end of tests using tunnel

src/main/java/com/stratio/qa/specs/DcosSpec.java, src/main/java/com/stratio/qa/specs/GosecSpec.java
- @dcos get version of management-ui and management-baas
- Creation of users and groups without data json. If the steps detects a deployed version of management-baas, it will use this one instead gosec-management. If management-baas is not deployed, it will get the old one (management).
- If the user/group already exists, a warning message is retrieved
=> [GS-2073] New steps to create users and groups with baas or management

CHANGELOG.md, src/main/java/com/stratio/qa/specs/CCTSpec.java
Se creó el método getHostIP, deprecando el antiguo método getMachineIp, pero no permitiamos obtener la IP interna.
Se ha añadido un argumento al método getHostIP para poder obtener tanto IP interna como externa de un servicio
=> [SPK-914] Complete new getHostIP method

src/main/java/com/stratio/qa/specs/CommonG.java, src/main/java/com/stratio/qa/specs/DcosSpec.java
Upgrate Discovery Token method with last versions.
Examples of use:
- Given I set sso token using host '!{DISCOVERY_HOST}/${DISCOVERY_ID:-discovery-qa}/auth' with user '${DCOS_TENANT1_OWNER_USER}' and password '${DCOS_TENANT1_OWNER_PASSWORD}' and tenant '${DCOS_TENANT1}' without host name verification with discovery cookie '${DCOS_TENANT1}-${DISCOVERY_ID:-discovery-qa}-auth-cookie'
- Given I obtain metabase id for user '${USER}' and password '${PASSWORD}' in endpoint 'https://!{DISCOVERY_HOST}/${DISCOVERY_ID:-discovery-qa}${DISCOVERY_SESSION:-/api/session}' and save in context cookies
=> [ROCK-2116] Handle Discovery Token

src/main/java/com/stratio/qa/clients/k8s/KubernetesClient.java, src/main/java/com/stratio/qa/specs/K8SSpec.java
@keos
Scenario: test
When I forward containerPort '9000' in localhostPort '9000' for service 'coverage-testsat-unified' in namespace 'spark'
Then I run 'curl http://127.0.0.1:9000/jobs/' locally
And I close port forward
=> [QATM-3590] Kubernetes Port forward steps

src/main/java/com/stratio/qa/specs/CommonG.java, src/main/java/com/stratio/qa/specs/DcosSpec.java, src/main/java/com/stratio/qa/specs/HookGSpec.java, src/main/java/com/stratio/qa/specs/K8SSpec.java, src/main/java/com/stratio/qa/utils/GosecSSOUtils.java
Se añade nuevo step para obtener cookies que utilizaremos en servicios desplegados en KEOS.
Probado con CCT y Gosec y parece que funciona OK
Nota: Es una primera aproximación, si finalmente hubiese front en KEOS o similar habría que dar una vuelta
Ejemplo:
@keos
Scenario: test
And I set sso keos token using host 'admin.golf.int' with user 'admin', password '1234' and tenant 'NONE'
When I securely send requests to 'admin.golf.int:443'
When I send a 'GET' request to '/service/cct-applications-query-service/v1/applications'
Then the service response status must be '200'
When I send a 'GET' request to '/baas/management/users'
Then the service response status must be '200'
=> [QATM-3626] Get _oauth2_proxy and stratio-cookie in KEOS
